/*
 * This source file was generated by the Gradle 'init' task
 */
package cz.tomkre.edu.githubactions;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MasterApplicationTest {
    @Test
    void shouldHandle() {}
}
