name: create-failure-issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      title:
        required: true
        description: 'Issue title'
      body:
        required: true
        description: 'Issue body'

jobs:
  create_issue_on_failure:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
          --header 'content-type: application/json' \
          --data '{
            "title": "Failure: ${{ inputs.title }}",
            "body": "Details: ${{ inputs.body }}"
          }'