name: External

on:
  workflow_run:
    workflows: [Main]
    types: [completed]
    branches:
      - 'rel/**'
      - '!rel/**-preprod'

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo 'running first step in external workflow'