run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

env:
  AUTHOR: ${{ vars.AUTHOR }}

jobs:
  master:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - uses: actions/checkout@v4
      - name: List repository contents
        run: ls
      - name: Get content of author.txt
        run: cat author.txt