run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ~/.master-data && echo 'master output data' > ~/.master-data/master-output
      - id: cache-master
        env:
          cache-name: master-cache
        uses: actions/checkout@v4
        with:
          path: ~/.master-data/master-output
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/.master-data/master-output') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Check for cache hit
        run: |
          echo "Cache hit: [${{ steps.cache-master.outputs.cache-hit }}]"
            

