name: Main

on:
  push:
    branches:
      - main
      - 'rel/**'
jobs:
  job_one:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: step_one
        run: |
          echo 'Running step_one of job_one' 
            

