name: Main

on:
  push:
    branches: [main]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret with code
        env:
          SAMPLE_VAR: ${{ github.event.head_commit.message }}
        run: echo $SAMPLE_VAR

