name: Master workflow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files
        run: ls
      - name: Greet author
        run: echo 'Hello, Tom!'

