run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  W: tkr-w

jobs:
  master_job:
    runs-on: ubuntu-latest
    env:
      J: tkr-j
    steps:
      - uses: actions/checkout@v4
      - name: List repository contents
        run: ls
      - name: Print variables
        env:
          S: tkr-s
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ env.W }}
          echo ${{ env.J }}
          echo ${{ env.S }}
          echo ${{ env.TOKEN }}