run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  verify:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_VF == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          [[ -f ${{ vars.FILE_TO_CHECK }} ]] || (echo "${{ vars.FILE_TO_CHECK }} fle needs to be added to ${{ github.repository }} !" && exit 1)
          echo "File ${{ vars.FILE_TO_CHECK }} exists"