run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
      - name: Get changelog version
        run: echo 'Changelog version - ${{ steps.changelog.outputs.version }}'
