run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: foo

jobs:
  master_job_one:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: python
    steps:
      - name: pwd
        run: pwd
      - name: Say hello
        run: print('Hello, Tom!')
  master_job_two:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bar
    steps:
      - name: pwd
        run: pwd
  master_job_three:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: print('Hello, Tom!')