name: Main

on:
  push:
    branches: [main]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret with code
        env:
          SAMPLE_CODE: secrets.SAMPLE_CODE
        run: echo ${{ env.SAMPLE_CODE }}

