run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  master_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print run url via context vars
        run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}