run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'master output data' > ~/.master-data/master-output
      - id: cache-master
        uses: actions/checkout@v4
        env:
          cache-name: master-cache
          ACTION_STEP_DEBUG: true
        with:
          path: ~/.master-data
          key: '${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/.master-data/master-output') }}'
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build
            ${{ runner.os }}
      - if: ${{ steps.cache-master.outputs.cache-hit == 'true' }}
        name: Check for cache hit
        run: echo 'Got cache hit on key'
            

