name: main

on:
  push:

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: step_one
        run: |
          echo 'Running step_one'
          exit 0
  job_two:
    runs-on: ubuntu-latest
    needs: [job_one]
    steps:
      - name: step_one
        run: |
          echo 'Running step_one'
          exit 1
          
