run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

env:
  AUTHOR: ${{ vars.AUTHOR }}

jobs:
  master:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: create new file
        run: echo 'cnt' > file-from-wf.txt
      - name: List repository contents
        run: ls