name: Master workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  master_job:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: List repository contents
        run: ls
      - name: Check version of ubuntu
        run: lsb_release -a