run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  master_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print on linux
        if: runner.os != 'Windows'
        run: echo "The runner's operating system is $RUNNER_OS."
      - name: Print on windows
        if: runner.os == 'Windows'
        run: echo "The runner's operating system is WINDOWS_"