name: Main

on:
  push:
    branches:
      - main
      - 'rel/**'
jobs:
  job_one:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: step_one
        run: |
          echo 'Running step_one of job_one'
          echo 'github.head_ref: ${{ github.head_ref }}'
          echo 'github.ref: ${{ github.ref }}'
            

