run-name: Master workflow run by @${{ github.actor }}

on:
  issues:
    types: [opened, edited, closed]

jobs:
  notify-for-issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'An issue was opened, edited or closed'
            

