run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  master_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print run url
        run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID