name: Main

on:
  push:

jobs:
  intro:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PAT Secret: ${{ secrets.PAT || 'def' }}"

  create-new-issue:
    permissions:
      issues: write
    strategy:
      matrix:
        prod: [pro1, prod2]
        level: [dev, prod]
    uses: rndrepos/common/.github/workflows/create-repo-issue3.yml@main
    secrets: inherit
    with:
      title: "${{ matrix.prod }} issue"
      body: "Update for ${{ matrix.level }}"
  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: |
          echo ${{ needs.create-new-issue.outputs.issue-number }}