name: main

on:
  pull_request:

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: handle
        run: |
          echo 'Label: ${{ contains(github.event.pull_request.labels.*.name, 'enhancement') }}'
          echo 'Label: ${{ contains(github.event.pull_request.labels.*.name, 'enhancementx') }}'
          echo 'contains ${{ contains('tomkre', 'tkr') }}'
          echo 'contains ${{ contains('tomkre', 'tom') }}'
          
