run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: app/build/libs
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: [build-and-test]
    environment:
      name: dev
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.DEV_VERSION }}
    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v4
        with:
          name: app.jar
      - name: release to dev
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ vars.DEV_VERSION }}
          token: ${{ secrets.DEV_TOKEN }}
          prerelease: true
          draft: true
          name: dev
          files: app.jar
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-and-test]
    environment:
      name: prod
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.PROD_VERSION }}
    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v4
        with:
          name: app.jar
      - name: GH release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ vars.PROD_VERSION }}
          token: ${{ secrets.PROD_TOKEN }}
          generate_release_notes: true
          name: Production
          files: app.jar