name: Master

on:
  push:
    branches:
      - main

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files
        run: ls
  job_two:
    runs-on: ubuntu-latest
    steps:
      - name: Greet author
        run: echo 'Hello, Tom!'


