name: main

on:
  pull_request:

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: handle
        run: |
          echo 'Label: ${{ github.event.pull_request.labels.*.name }}'
          echo 'contains ${{ contains('tomkre', 'tkr') }}'
          echo 'contains ${{ contains('tomkre', 'tom') }}'
          
