run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches:
      - ma*n

jobs:
  notify-for-issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'An action triggered by glob pattern'
            

