name: Main

on:
  push:
    branches:
      - main
      - 'rel/**'

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo 'Starting job and sleep for few seconds'
          sleep 10
          echo 'Finishing job2'
            

