name: Main

on:
  push:

jobs:
  job_one:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: check-os
        if: runner.os != 'Windows'
        run: echo "The runner's operation system is $RUNNER_OS."
      - name: check-os
        if: runner.os == 'Windows'
        run: echo "The runner's operation system is WINDOWS"
  job_two:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feat/one'
    steps:
      - name: feat-one job
        run: echo 'Running job for feat/one branch'