name: Main

on:
  push:
    branches:
      - main
      - 'rel/**'
jobs:
  one:
    runs-on: ubuntu-latest
    concurrency: master
    steps:
      - name: First step
        run: |
          echo 'Starting job (by ${{ github.ref }}) and sleep for few seconds'
          sleep 10
          echo 'Finishing job3'
            

