name: Main

on:
  push:

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(steps) }}'