run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      file-to-cache: ~/.master-data/master-output-001
    steps:
      - uses: actions/checkout@v4
      - run: mkdir ~/.master-data && echo 'master output data' > ${{ env.file-to-cache }}
      - id: cache-master
        env:
          cache-name: master-cache
          ACTIONS_STEP_DEBUG: true
        uses: actions/cache@v4
        with:
          path: ${{ env.file-to-cache }}
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.java') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-master.outputs.cache-hit == 'true' }}
        name: Check for cache hit
        run: |
          echo "Got cache hit on key3"
          echo "Github SHA: ${{ github.sha }}"
            

