run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

env:
  AUTHOR: ${{ vars.AUTHOR }}

jobs:
  master:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issues using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Issue from WF",
            "body": "This issue was create from WF by ${{ env.AUTHOR }}"
          }' \
          --fail