run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  master_job_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pwd
        run: pwd
      - name: ls
        run: ls