run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    paths:
      - '.github/workflows/**'
      - '!.github/workflows/main.yml.bak'

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.WF }}' \
          -H 'Accept: application/vnd.github.v3+json' \
          -d '{
            "ref": "main",
            "inputs": {
              "title": "Automated workflow failure issue for commit ${{ github.sha }}",
              "body": "This issue was automatically created by the GitHub Action workflow ** ${{ github.workflow }} **"
            }
          }' \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-failure-issue.yml/dispatches"
            

