name: Master workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  master_job:
    runs-on: [self-hosted, master-one]
    steps:
      - uses: actions/checkout@v4
      - name: List home directory contents
        run: ls /home/ec2-user
      - name: Create a file in home directory
        run: echo 'tomkre' > /home/ec2-user/author.txt