name: Main

on:
  push:
    branches:
      - main
      - 'rel/**'
jobs:
  one:
    runs-on: ubuntu-latest
    concurrency:
      group: master
      cancel-in-progress: true
    steps:
      - name: First step
        run: |
          echo 'Starting job (by ${{ github.ref }}) and sleep for few seconds'
          sleep 10
          echo 'Finishing job1'
            

