run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  master_job_one:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/edu-github-actions
    steps:
      - name: pwd
        run: pwd
      - name: ls
        run: ls