run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build project
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
            

