name: Main

on:
  push:

jobs:
  job_one:
    strategy:
      matrix:
        be: [spring_boot, quarkus]
        fe: [angular, react]
    uses: ./.github/workflows/sw_project.yml
    with:
      be: ${{ matrix.be }}
      fe: ${{ matrix.fe }}
  job_two:
    runs-on: ubuntu-latest
    needs: [job_one]
    steps:
      - name: Step one in job_two
        run: |
          echo 'Result: ${{ needs.job_one.outputs.result }}'