run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches-ignore:
      - ignore

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'An action triggered by glob pattern'
            

