name: Main

on:
  push:

jobs:
  create-new-issue:
    permissions:
      issues: write
    uses: ./.github/workflows/create-repo-issue3.yml
    secrets: inherit
    with:
      title: "issue ${{ github.sha }}"
      body: "Issue body"
  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: |
          echo ${{ needs.create-new-issue.outputs.issue-number }}