run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: test
            

