run-name: Master workflow run by @${{ github.actor }}

on:
  push:
    paths:
      - .github/workflows/**
      - .github/workflows/main.yml.bak

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'An action triggered by glob pattern'
            

