name: Master workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  master_job:
    runs-on: self-hosted
    steps:
      - name: List home directory contents
        run: ls /home/ec2-user



