run-name: Master workflow run by @${{ github.actor }}

on:
  issues:

jobs:
  notify-for-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Display notification
        run: echo 'Something happened with an issue'
            

