name: manual

on:
  workflow_run:
    workflows: [main]
    types:
      - completed

jobs:
  handle:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: handle
        run: echo 'Manual handle'
          
